//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using MovieBooking.Model.Entities;

namespace MovieBooking.DAL
{
    public partial class MovieBookingEntitiesContext : ObjectContext
    {
        public const string ConnectionString = "name=MovieBookingEntitiesContext";
        public const string ContainerName = "MovieBookingEntitiesContext";
    
        #region Constructors
    
        public MovieBookingEntitiesContext()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public MovieBookingEntitiesContext(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public MovieBookingEntitiesContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<aspnet_Membership> aspnet_Membership
        {
            get { return _aspnet_Membership  ?? (_aspnet_Membership = CreateObjectSet<aspnet_Membership>("aspnet_Membership")); }
        }
        private ObjectSet<aspnet_Membership> _aspnet_Membership;
    
        public ObjectSet<aspnet_Users> aspnet_Users
        {
            get { return _aspnet_Users  ?? (_aspnet_Users = CreateObjectSet<aspnet_Users>("aspnet_Users")); }
        }
        private ObjectSet<aspnet_Users> _aspnet_Users;
    
        public ObjectSet<mb_Movie> mb_Movie
        {
            get { return _mb_Movie  ?? (_mb_Movie = CreateObjectSet<mb_Movie>("mb_Movie")); }
        }
        private ObjectSet<mb_Movie> _mb_Movie;
    
        public ObjectSet<mb_Movie_Item> mb_Movie_Item
        {
            get { return _mb_Movie_Item  ?? (_mb_Movie_Item = CreateObjectSet<mb_Movie_Item>("mb_Movie_Item")); }
        }
        private ObjectSet<mb_Movie_Item> _mb_Movie_Item;
    
        public ObjectSet<mb_MovieBooking> mb_MovieBooking
        {
            get { return _mb_MovieBooking  ?? (_mb_MovieBooking = CreateObjectSet<mb_MovieBooking>("mb_MovieBooking")); }
        }
        private ObjectSet<mb_MovieBooking> _mb_MovieBooking;
    
        public ObjectSet<mb_MovieBooking_Item> mb_MovieBooking_Item
        {
            get { return _mb_MovieBooking_Item  ?? (_mb_MovieBooking_Item = CreateObjectSet<mb_MovieBooking_Item>("mb_MovieBooking_Item")); }
        }
        private ObjectSet<mb_MovieBooking_Item> _mb_MovieBooking_Item;
    
        public ObjectSet<mb_MovieBooking_Trans> mb_MovieBooking_Trans
        {
            get { return _mb_MovieBooking_Trans  ?? (_mb_MovieBooking_Trans = CreateObjectSet<mb_MovieBooking_Trans>("mb_MovieBooking_Trans")); }
        }
        private ObjectSet<mb_MovieBooking_Trans> _mb_MovieBooking_Trans;
    
        public ObjectSet<mb_MovieSchedule> mb_MovieSchedule
        {
            get { return _mb_MovieSchedule  ?? (_mb_MovieSchedule = CreateObjectSet<mb_MovieSchedule>("mb_MovieSchedule")); }
        }
        private ObjectSet<mb_MovieSchedule> _mb_MovieSchedule;
    
        public ObjectSet<mb_MovieSchedule_Item> mb_MovieSchedule_Item
        {
            get { return _mb_MovieSchedule_Item  ?? (_mb_MovieSchedule_Item = CreateObjectSet<mb_MovieSchedule_Item>("mb_MovieSchedule_Item")); }
        }
        private ObjectSet<mb_MovieSchedule_Item> _mb_MovieSchedule_Item;
    
        public ObjectSet<mb_Payment> mb_Payment
        {
            get { return _mb_Payment  ?? (_mb_Payment = CreateObjectSet<mb_Payment>("mb_Payment")); }
        }
        private ObjectSet<mb_Payment> _mb_Payment;
    
        public ObjectSet<mb_RegisteredUser> mb_RegisteredUser
        {
            get { return _mb_RegisteredUser  ?? (_mb_RegisteredUser = CreateObjectSet<mb_RegisteredUser>("mb_RegisteredUser")); }
        }
        private ObjectSet<mb_RegisteredUser> _mb_RegisteredUser;
    
        public ObjectSet<mb_SystemParameter> mb_SystemParameter
        {
            get { return _mb_SystemParameter  ?? (_mb_SystemParameter = CreateObjectSet<mb_SystemParameter>("mb_SystemParameter")); }
        }
        private ObjectSet<mb_SystemParameter> _mb_SystemParameter;
    
        public ObjectSet<mb_Theatre> mb_Theatre
        {
            get { return _mb_Theatre  ?? (_mb_Theatre = CreateObjectSet<mb_Theatre>("mb_Theatre")); }
        }
        private ObjectSet<mb_Theatre> _mb_Theatre;
    
        public ObjectSet<aspnet_Applications> aspnet_Applications
        {
            get { return _aspnet_Applications  ?? (_aspnet_Applications = CreateObjectSet<aspnet_Applications>("aspnet_Applications")); }
        }
        private ObjectSet<aspnet_Applications> _aspnet_Applications;
    
        public ObjectSet<aspnet_Paths> aspnet_Paths
        {
            get { return _aspnet_Paths  ?? (_aspnet_Paths = CreateObjectSet<aspnet_Paths>("aspnet_Paths")); }
        }
        private ObjectSet<aspnet_Paths> _aspnet_Paths;
    
        public ObjectSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers
        {
            get { return _aspnet_PersonalizationAllUsers  ?? (_aspnet_PersonalizationAllUsers = CreateObjectSet<aspnet_PersonalizationAllUsers>("aspnet_PersonalizationAllUsers")); }
        }
        private ObjectSet<aspnet_PersonalizationAllUsers> _aspnet_PersonalizationAllUsers;
    
        public ObjectSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser
        {
            get { return _aspnet_PersonalizationPerUser  ?? (_aspnet_PersonalizationPerUser = CreateObjectSet<aspnet_PersonalizationPerUser>("aspnet_PersonalizationPerUser")); }
        }
        private ObjectSet<aspnet_PersonalizationPerUser> _aspnet_PersonalizationPerUser;
    
        public ObjectSet<aspnet_Profile> aspnet_Profile
        {
            get { return _aspnet_Profile  ?? (_aspnet_Profile = CreateObjectSet<aspnet_Profile>("aspnet_Profile")); }
        }
        private ObjectSet<aspnet_Profile> _aspnet_Profile;
    
        public ObjectSet<aspnet_Roles> aspnet_Roles
        {
            get { return _aspnet_Roles  ?? (_aspnet_Roles = CreateObjectSet<aspnet_Roles>("aspnet_Roles")); }
        }
        private ObjectSet<aspnet_Roles> _aspnet_Roles;
    
        public ObjectSet<aspnet_SchemaVersions> aspnet_SchemaVersions
        {
            get { return _aspnet_SchemaVersions  ?? (_aspnet_SchemaVersions = CreateObjectSet<aspnet_SchemaVersions>("aspnet_SchemaVersions")); }
        }
        private ObjectSet<aspnet_SchemaVersions> _aspnet_SchemaVersions;
    
        public ObjectSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events
        {
            get { return _aspnet_WebEvent_Events  ?? (_aspnet_WebEvent_Events = CreateObjectSet<aspnet_WebEvent_Events>("aspnet_WebEvent_Events")); }
        }
        private ObjectSet<aspnet_WebEvent_Events> _aspnet_WebEvent_Events;
    
        public ObjectSet<mb_Hall> mb_Hall
        {
            get { return _mb_Hall  ?? (_mb_Hall = CreateObjectSet<mb_Hall>("mb_Hall")); }
        }
        private ObjectSet<mb_Hall> _mb_Hall;
    
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get { return _sysdiagrams  ?? (_sysdiagrams = CreateObjectSet<sysdiagram>("sysdiagrams")); }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion
    }
}
