//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MovieBooking.BLL.POCOModel
{
    public partial class mb_MovieSchedule
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MovieID
        {
            get { return _movieID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_movieID != value)
                    {
                        if (mb_Movie != null && mb_Movie.ID != value)
                        {
                            mb_Movie = null;
                        }
                        _movieID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _movieID;
    
        public virtual Nullable<int> TheatreID
        {
            get { return _theatreID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_theatreID != value)
                    {
                        if (mb_Theatre != null && mb_Theatre.ID != value)
                        {
                            mb_Theatre = null;
                        }
                        _theatreID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _theatreID;
    
        public virtual string HallID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ScheduleDate
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Price
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual mb_Movie mb_Movie
        {
            get { return _mb_Movie; }
            set
            {
                if (!ReferenceEquals(_mb_Movie, value))
                {
                    var previousValue = _mb_Movie;
                    _mb_Movie = value;
                    Fixupmb_Movie(previousValue);
                }
            }
        }
        private mb_Movie _mb_Movie;
    
        public virtual ICollection<mb_MovieBooking> mb_MovieBooking
        {
            get
            {
                if (_mb_MovieBooking == null)
                {
                    var newCollection = new FixupCollection<mb_MovieBooking>();
                    newCollection.CollectionChanged += Fixupmb_MovieBooking;
                    _mb_MovieBooking = newCollection;
                }
                return _mb_MovieBooking;
            }
            set
            {
                if (!ReferenceEquals(_mb_MovieBooking, value))
                {
                    var previousValue = _mb_MovieBooking as FixupCollection<mb_MovieBooking>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmb_MovieBooking;
                    }
                    _mb_MovieBooking = value;
                    var newValue = value as FixupCollection<mb_MovieBooking>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmb_MovieBooking;
                    }
                }
            }
        }
        private ICollection<mb_MovieBooking> _mb_MovieBooking;
    
        public virtual ICollection<mb_MovieSchedule_Item> mb_MovieSchedule_Item
        {
            get
            {
                if (_mb_MovieSchedule_Item == null)
                {
                    var newCollection = new FixupCollection<mb_MovieSchedule_Item>();
                    newCollection.CollectionChanged += Fixupmb_MovieSchedule_Item;
                    _mb_MovieSchedule_Item = newCollection;
                }
                return _mb_MovieSchedule_Item;
            }
            set
            {
                if (!ReferenceEquals(_mb_MovieSchedule_Item, value))
                {
                    var previousValue = _mb_MovieSchedule_Item as FixupCollection<mb_MovieSchedule_Item>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmb_MovieSchedule_Item;
                    }
                    _mb_MovieSchedule_Item = value;
                    var newValue = value as FixupCollection<mb_MovieSchedule_Item>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmb_MovieSchedule_Item;
                    }
                }
            }
        }
        private ICollection<mb_MovieSchedule_Item> _mb_MovieSchedule_Item;
    
        public virtual mb_Theatre mb_Theatre
        {
            get { return _mb_Theatre; }
            set
            {
                if (!ReferenceEquals(_mb_Theatre, value))
                {
                    var previousValue = _mb_Theatre;
                    _mb_Theatre = value;
                    Fixupmb_Theatre(previousValue);
                }
            }
        }
        private mb_Theatre _mb_Theatre;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixupmb_Movie(mb_Movie previousValue)
        {
            if (previousValue != null && previousValue.mb_MovieSchedule.Contains(this))
            {
                previousValue.mb_MovieSchedule.Remove(this);
            }
    
            if (mb_Movie != null)
            {
                if (!mb_Movie.mb_MovieSchedule.Contains(this))
                {
                    mb_Movie.mb_MovieSchedule.Add(this);
                }
                if (MovieID != mb_Movie.ID)
                {
                    MovieID = mb_Movie.ID;
                }
            }
            else if (!_settingFK)
            {
                MovieID = null;
            }
        }
    
        private void Fixupmb_Theatre(mb_Theatre previousValue)
        {
            if (previousValue != null && previousValue.mb_MovieSchedule.Contains(this))
            {
                previousValue.mb_MovieSchedule.Remove(this);
            }
    
            if (mb_Theatre != null)
            {
                if (!mb_Theatre.mb_MovieSchedule.Contains(this))
                {
                    mb_Theatre.mb_MovieSchedule.Add(this);
                }
                if (TheatreID != mb_Theatre.ID)
                {
                    TheatreID = mb_Theatre.ID;
                }
            }
            else if (!_settingFK)
            {
                TheatreID = null;
            }
        }
    
        private void Fixupmb_MovieBooking(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mb_MovieBooking item in e.NewItems)
                {
                    item.mb_MovieSchedule = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mb_MovieBooking item in e.OldItems)
                {
                    if (ReferenceEquals(item.mb_MovieSchedule, this))
                    {
                        item.mb_MovieSchedule = null;
                    }
                }
            }
        }
    
        private void Fixupmb_MovieSchedule_Item(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mb_MovieSchedule_Item item in e.NewItems)
                {
                    item.mb_MovieSchedule = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mb_MovieSchedule_Item item in e.OldItems)
                {
                    if (ReferenceEquals(item.mb_MovieSchedule, this))
                    {
                        item.mb_MovieSchedule = null;
                    }
                }
            }
        }

        #endregion
    }
}
