//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MovieBooking.BLL.POCOModel
{
    public partial class mb_SystemParameter
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Category
        {
            get;
            set;
        }
    
        public virtual string ItemName
        {
            get;
            set;
        }
    
        public virtual string ItemValue
        {
            get;
            set;
        }
    
        public virtual Nullable<short> SortOrder
        {
            get;
            set;
        }
    
        public virtual string Remarks
        {
            get;
            set;
        }
    
        public virtual bool Active
        {
            get;
            set;
        }

        #endregion
    }
}
