//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace MovieBooking.Model.Entities
{
    [DataContract]
    public partial class mb_Hall
    {
        #region Primitive Properties
      
        [DataMember]
        public virtual int ID
        {
            get;
            set;
        }
        [DataMember]
        public virtual int TheatreID
        {
            get { return _theatreID; }
            set
            {
                if (_theatreID != value)
                {
                    if (mb_Theatre != null && mb_Theatre.ID != value)
                    {
                        mb_Theatre = null;
                    }
                    _theatreID = value;
                }
            }
        }
        private int _theatreID;
        [DataMember]    
        public virtual string HallName
        {
            get;
            set;
        }
        [DataMember]  
        public virtual int TotalSeats
        {
            get;
            set;
        }
        [DataMember]  
        public virtual bool Active
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual mb_Theatre mb_Theatre
        {
            get { return _mb_Theatre; }
            set
            {
                if (!ReferenceEquals(_mb_Theatre, value))
                {
                    var previousValue = _mb_Theatre;
                    _mb_Theatre = value;
                    Fixupmb_Theatre(previousValue);
                }
            }
        }
        private mb_Theatre _mb_Theatre;
    
        public virtual ICollection<mb_MovieSchedule> mb_MovieSchedule
        {
            get
            {
                if (_mb_MovieSchedule == null)
                {
                    var newCollection = new FixupCollection<mb_MovieSchedule>();
                    newCollection.CollectionChanged += Fixupmb_MovieSchedule;
                    _mb_MovieSchedule = newCollection;
                }
                return _mb_MovieSchedule;
            }
            set
            {
                if (!ReferenceEquals(_mb_MovieSchedule, value))
                {
                    var previousValue = _mb_MovieSchedule as FixupCollection<mb_MovieSchedule>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmb_MovieSchedule;
                    }
                    _mb_MovieSchedule = value;
                    var newValue = value as FixupCollection<mb_MovieSchedule>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmb_MovieSchedule;
                    }
                }
            }
        }
        private ICollection<mb_MovieSchedule> _mb_MovieSchedule;

        #endregion
        #region Association Fixup
    
        private void Fixupmb_Theatre(mb_Theatre previousValue)
        {
            if (previousValue != null && previousValue.mb_Hall.Contains(this))
            {
                previousValue.mb_Hall.Remove(this);
            }
    
            if (mb_Theatre != null)
            {
                if (!mb_Theatre.mb_Hall.Contains(this))
                {
                    mb_Theatre.mb_Hall.Add(this);
                }
                if (TheatreID != mb_Theatre.ID)
                {
                    TheatreID = mb_Theatre.ID;
                }
            }
        }
    
        private void Fixupmb_MovieSchedule(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mb_MovieSchedule item in e.NewItems)
                {
                    item.mb_Hall = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mb_MovieSchedule item in e.OldItems)
                {
                    if (ReferenceEquals(item.mb_Hall, this))
                    {
                        item.mb_Hall = null;
                    }
                }
            }
        }

        #endregion
    }
}
