//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MovieBooking.Model.Entities
{
    public partial class mb_Movie
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string MovieName
        {
            get;
            set;
        }
    
        public virtual string LanguageID
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual string RatingID
        {
            get;
            set;
        }
    
        public virtual Nullable<short> RunningDuration
        {
            get;
            set;
        }
    
        public virtual bool Active
        {
            get;
            set;
        }
    
        public virtual string trailer_url
        {
            get;
            set;
        }
    
        public virtual string genre
        {
            get;
            set;
        }
    
        public virtual string ImageMoviePath
        {
            get;
            set;
        }
    
        public virtual string CastDescription
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mb_Movie_Item> mb_Movie_Item
        {
            get
            {
                if (_mb_Movie_Item == null)
                {
                    var newCollection = new FixupCollection<mb_Movie_Item>();
                    newCollection.CollectionChanged += Fixupmb_Movie_Item;
                    _mb_Movie_Item = newCollection;
                }
                return _mb_Movie_Item;
            }
            set
            {
                if (!ReferenceEquals(_mb_Movie_Item, value))
                {
                    var previousValue = _mb_Movie_Item as FixupCollection<mb_Movie_Item>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmb_Movie_Item;
                    }
                    _mb_Movie_Item = value;
                    var newValue = value as FixupCollection<mb_Movie_Item>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmb_Movie_Item;
                    }
                }
            }
        }
        private ICollection<mb_Movie_Item> _mb_Movie_Item;
    
        public virtual ICollection<mb_MovieSchedule> mb_MovieSchedule
        {
            get
            {
                if (_mb_MovieSchedule == null)
                {
                    var newCollection = new FixupCollection<mb_MovieSchedule>();
                    newCollection.CollectionChanged += Fixupmb_MovieSchedule;
                    _mb_MovieSchedule = newCollection;
                }
                return _mb_MovieSchedule;
            }
            set
            {
                if (!ReferenceEquals(_mb_MovieSchedule, value))
                {
                    var previousValue = _mb_MovieSchedule as FixupCollection<mb_MovieSchedule>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmb_MovieSchedule;
                    }
                    _mb_MovieSchedule = value;
                    var newValue = value as FixupCollection<mb_MovieSchedule>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmb_MovieSchedule;
                    }
                }
            }
        }
        private ICollection<mb_MovieSchedule> _mb_MovieSchedule;

        #endregion
        #region Association Fixup
    
        private void Fixupmb_Movie_Item(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mb_Movie_Item item in e.NewItems)
                {
                    item.mb_Movie = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mb_Movie_Item item in e.OldItems)
                {
                    if (ReferenceEquals(item.mb_Movie, this))
                    {
                        item.mb_Movie = null;
                    }
                }
            }
        }
    
        private void Fixupmb_MovieSchedule(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mb_MovieSchedule item in e.NewItems)
                {
                    item.mb_Movie = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mb_MovieSchedule item in e.OldItems)
                {
                    if (ReferenceEquals(item.mb_Movie, this))
                    {
                        item.mb_Movie = null;
                    }
                }
            }
        }

        #endregion
    }
}
