//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MovieBooking.Model.Entities
{
    public partial class mb_RegisteredUser
    {
        #region Primitive Properties
    
        public virtual System.Guid UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (aspnet_Membership != null && aspnet_Membership.UserId != value)
                    {
                        aspnet_Membership = null;
                    }
                    _userId = value;
                }
            }
        }
        private System.Guid _userId;
    
        public virtual string NRIC
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DOB
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string PostalCode
        {
            get;
            set;
        }
    
        public virtual string BankName
        {
            get;
            set;
        }
    
        public virtual string AccountNo
        {
            get;
            set;
        }
    
        public virtual bool Active
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual aspnet_Membership aspnet_Membership
        {
            get { return _aspnet_Membership; }
            set
            {
                if (!ReferenceEquals(_aspnet_Membership, value))
                {
                    var previousValue = _aspnet_Membership;
                    _aspnet_Membership = value;
                    Fixupaspnet_Membership(previousValue);
                }
            }
        }
        private aspnet_Membership _aspnet_Membership;
    
        public virtual ICollection<mb_MovieBooking> mb_MovieBooking
        {
            get
            {
                if (_mb_MovieBooking == null)
                {
                    var newCollection = new FixupCollection<mb_MovieBooking>();
                    newCollection.CollectionChanged += Fixupmb_MovieBooking;
                    _mb_MovieBooking = newCollection;
                }
                return _mb_MovieBooking;
            }
            set
            {
                if (!ReferenceEquals(_mb_MovieBooking, value))
                {
                    var previousValue = _mb_MovieBooking as FixupCollection<mb_MovieBooking>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmb_MovieBooking;
                    }
                    _mb_MovieBooking = value;
                    var newValue = value as FixupCollection<mb_MovieBooking>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmb_MovieBooking;
                    }
                }
            }
        }
        private ICollection<mb_MovieBooking> _mb_MovieBooking;

        #endregion
        #region Association Fixup
    
        private void Fixupaspnet_Membership(aspnet_Membership previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.mb_RegisteredUser, this))
            {
                previousValue.mb_RegisteredUser = null;
            }
    
            if (aspnet_Membership != null)
            {
                aspnet_Membership.mb_RegisteredUser = this;
                if (UserId != aspnet_Membership.UserId)
                {
                    UserId = aspnet_Membership.UserId;
                }
            }
        }
    
        private void Fixupmb_MovieBooking(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mb_MovieBooking item in e.NewItems)
                {
                    item.mb_RegisteredUser = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mb_MovieBooking item in e.OldItems)
                {
                    if (ReferenceEquals(item.mb_RegisteredUser, this))
                    {
                        item.mb_RegisteredUser = null;
                    }
                }
            }
        }

        #endregion
    }
}
