//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieBooking.UI.Maintenance.HallListService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HallListService.IHallListService")]
    public interface IHallListService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHallListService/GetHallList", ReplyAction="http://tempuri.org/IHallListService/GetHallListResponse")]
        MovieBooking.BLL.Entities.Hall[] GetHallList(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHallListService/updateHall", ReplyAction="http://tempuri.org/IHallListService/updateHallResponse")]
        bool updateHall(MovieBooking.BLL.Entities.Hall myHall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHallListService/addHall", ReplyAction="http://tempuri.org/IHallListService/addHallResponse")]
        bool addHall(MovieBooking.BLL.Entities.Hall myHall);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHallListServiceChannel : MovieBooking.UI.Maintenance.HallListService.IHallListService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HallListServiceClient : System.ServiceModel.ClientBase<MovieBooking.UI.Maintenance.HallListService.IHallListService>, MovieBooking.UI.Maintenance.HallListService.IHallListService {
        
        public HallListServiceClient() {
        }
        
        public HallListServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HallListServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HallListServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HallListServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MovieBooking.BLL.Entities.Hall[] GetHallList(int Id) {
            return base.Channel.GetHallList(Id);
        }
        
        public bool updateHall(MovieBooking.BLL.Entities.Hall myHall) {
            return base.Channel.updateHall(myHall);
        }
        
        public bool addHall(MovieBooking.BLL.Entities.Hall myHall) {
            return base.Channel.addHall(myHall);
        }
    }
}
