//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieBooking.UI.Maintenance.MovieScheduleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovieSchedule", Namespace="http://schemas.datacontract.org/2004/07/MovieBooking.SI.Web")]
    [System.SerializableAttribute()]
    public partial class MovieSchedule : MovieBooking.BLL.Entities.Movie, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovieScheduleService.IMovieScheduleService")]
    public interface IMovieScheduleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieScheduleService/GetMovies", ReplyAction="http://tempuri.org/IMovieScheduleService/GetMoviesResponse")]
        MovieBooking.UI.Maintenance.MovieScheduleService.MovieSchedule[] GetMovies();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovieScheduleServiceChannel : MovieBooking.UI.Maintenance.MovieScheduleService.IMovieScheduleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieScheduleServiceClient : System.ServiceModel.ClientBase<MovieBooking.UI.Maintenance.MovieScheduleService.IMovieScheduleService>, MovieBooking.UI.Maintenance.MovieScheduleService.IMovieScheduleService {
        
        public MovieScheduleServiceClient() {
        }
        
        public MovieScheduleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieScheduleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieScheduleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieScheduleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MovieBooking.UI.Maintenance.MovieScheduleService.MovieSchedule[] GetMovies() {
            return base.Channel.GetMovies();
        }
    }
}
