//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MovieBooking.BLL.POCOModel
{
    public partial class mb_MovieBooking
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string BookingRef
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> MemberID
        {
            get { return _memberID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_memberID != value)
                    {
                        if (mb_RegisteredUser != null && mb_RegisteredUser.UserId != value)
                        {
                            mb_RegisteredUser = null;
                        }
                        _memberID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _memberID;
    
        public virtual Nullable<int> ScheduleID
        {
            get { return _scheduleID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_scheduleID != value)
                    {
                        if (mb_MovieSchedule != null && mb_MovieSchedule.ID != value)
                        {
                            mb_MovieSchedule = null;
                        }
                        _scheduleID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _scheduleID;
    
        public virtual Nullable<System.DateTime> BookingDate
        {
            get;
            set;
        }
    
        public virtual string StatusID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mb_MovieBooking_Item> mb_MovieBooking_Item
        {
            get
            {
                if (_mb_MovieBooking_Item == null)
                {
                    var newCollection = new FixupCollection<mb_MovieBooking_Item>();
                    newCollection.CollectionChanged += Fixupmb_MovieBooking_Item;
                    _mb_MovieBooking_Item = newCollection;
                }
                return _mb_MovieBooking_Item;
            }
            set
            {
                if (!ReferenceEquals(_mb_MovieBooking_Item, value))
                {
                    var previousValue = _mb_MovieBooking_Item as FixupCollection<mb_MovieBooking_Item>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmb_MovieBooking_Item;
                    }
                    _mb_MovieBooking_Item = value;
                    var newValue = value as FixupCollection<mb_MovieBooking_Item>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmb_MovieBooking_Item;
                    }
                }
            }
        }
        private ICollection<mb_MovieBooking_Item> _mb_MovieBooking_Item;
    
        public virtual mb_MovieSchedule mb_MovieSchedule
        {
            get { return _mb_MovieSchedule; }
            set
            {
                if (!ReferenceEquals(_mb_MovieSchedule, value))
                {
                    var previousValue = _mb_MovieSchedule;
                    _mb_MovieSchedule = value;
                    Fixupmb_MovieSchedule(previousValue);
                }
            }
        }
        private mb_MovieSchedule _mb_MovieSchedule;
    
        public virtual mb_RegisteredUser mb_RegisteredUser
        {
            get { return _mb_RegisteredUser; }
            set
            {
                if (!ReferenceEquals(_mb_RegisteredUser, value))
                {
                    var previousValue = _mb_RegisteredUser;
                    _mb_RegisteredUser = value;
                    Fixupmb_RegisteredUser(previousValue);
                }
            }
        }
        private mb_RegisteredUser _mb_RegisteredUser;
    
        public virtual ICollection<mb_MovieBooking_Trans> mb_MovieBooking_Trans
        {
            get
            {
                if (_mb_MovieBooking_Trans == null)
                {
                    var newCollection = new FixupCollection<mb_MovieBooking_Trans>();
                    newCollection.CollectionChanged += Fixupmb_MovieBooking_Trans;
                    _mb_MovieBooking_Trans = newCollection;
                }
                return _mb_MovieBooking_Trans;
            }
            set
            {
                if (!ReferenceEquals(_mb_MovieBooking_Trans, value))
                {
                    var previousValue = _mb_MovieBooking_Trans as FixupCollection<mb_MovieBooking_Trans>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmb_MovieBooking_Trans;
                    }
                    _mb_MovieBooking_Trans = value;
                    var newValue = value as FixupCollection<mb_MovieBooking_Trans>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmb_MovieBooking_Trans;
                    }
                }
            }
        }
        private ICollection<mb_MovieBooking_Trans> _mb_MovieBooking_Trans;
    
        public virtual ICollection<mb_Payment> mb_Payment
        {
            get
            {
                if (_mb_Payment == null)
                {
                    var newCollection = new FixupCollection<mb_Payment>();
                    newCollection.CollectionChanged += Fixupmb_Payment;
                    _mb_Payment = newCollection;
                }
                return _mb_Payment;
            }
            set
            {
                if (!ReferenceEquals(_mb_Payment, value))
                {
                    var previousValue = _mb_Payment as FixupCollection<mb_Payment>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmb_Payment;
                    }
                    _mb_Payment = value;
                    var newValue = value as FixupCollection<mb_Payment>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmb_Payment;
                    }
                }
            }
        }
        private ICollection<mb_Payment> _mb_Payment;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixupmb_MovieSchedule(mb_MovieSchedule previousValue)
        {
            if (previousValue != null && previousValue.mb_MovieBooking.Contains(this))
            {
                previousValue.mb_MovieBooking.Remove(this);
            }
    
            if (mb_MovieSchedule != null)
            {
                if (!mb_MovieSchedule.mb_MovieBooking.Contains(this))
                {
                    mb_MovieSchedule.mb_MovieBooking.Add(this);
                }
                if (ScheduleID != mb_MovieSchedule.ID)
                {
                    ScheduleID = mb_MovieSchedule.ID;
                }
            }
            else if (!_settingFK)
            {
                ScheduleID = null;
            }
        }
    
        private void Fixupmb_RegisteredUser(mb_RegisteredUser previousValue)
        {
            if (previousValue != null && previousValue.mb_MovieBooking.Contains(this))
            {
                previousValue.mb_MovieBooking.Remove(this);
            }
    
            if (mb_RegisteredUser != null)
            {
                if (!mb_RegisteredUser.mb_MovieBooking.Contains(this))
                {
                    mb_RegisteredUser.mb_MovieBooking.Add(this);
                }
                if (MemberID != mb_RegisteredUser.UserId)
                {
                    MemberID = mb_RegisteredUser.UserId;
                }
            }
            else if (!_settingFK)
            {
                MemberID = null;
            }
        }
    
        private void Fixupmb_MovieBooking_Item(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mb_MovieBooking_Item item in e.NewItems)
                {
                    item.mb_MovieBooking = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mb_MovieBooking_Item item in e.OldItems)
                {
                    if (ReferenceEquals(item.mb_MovieBooking, this))
                    {
                        item.mb_MovieBooking = null;
                    }
                }
            }
        }
    
        private void Fixupmb_MovieBooking_Trans(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mb_MovieBooking_Trans item in e.NewItems)
                {
                    item.mb_MovieBooking = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mb_MovieBooking_Trans item in e.OldItems)
                {
                    if (ReferenceEquals(item.mb_MovieBooking, this))
                    {
                        item.mb_MovieBooking = null;
                    }
                }
            }
        }
    
        private void Fixupmb_Payment(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mb_Payment item in e.NewItems)
                {
                    item.mb_MovieBooking = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mb_Payment item in e.OldItems)
                {
                    if (ReferenceEquals(item.mb_MovieBooking, this))
                    {
                        item.mb_MovieBooking = null;
                    }
                }
            }
        }

        #endregion
    }
}
