//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using MovieBooking.DAL.Entities;
using System.Linq;

namespace MovieBooking.BLL.Entities
{
    public partial class RegisteredUser
    {
        #region Primitive Properties
    
        public virtual System.Guid UserId
        {
            get;
            set;
        }
    
        public virtual string NRIC
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DOB
        {
            get;
            set;
        }
    
        public virtual bool IsDeleted
        {
            get;
            set;
        }

        #endregion

        /// <summary>
        /// Gets Registered User
        /// </summary>
        public RegisteredUser Get(System.Guid _userId)
        {
            using (DAL.Entities.Entities ctx = new DAL.Entities.Entities())
            {
                var query = from p in ctx.RegisteredUsers
                            where p.UserId == _userId
                            select p;

                return new RegisteredUser() { UserId = query.First().UserId };
                
            }
        }

        public void Insert()
        {
            using (DAL.Entities.Entities ctx = new DAL.Entities.Entities())
            {
                DAL.Entities.RegisteredUser _user = new DAL.Entities.RegisteredUser() { UserId = this.UserId, NRIC = this.NRIC, DOB = this.DOB };
                ctx.AddToRegisteredUsers(_user);
                ctx.SaveChanges();
            }
        }
    }
}
