//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MovieBooking.Model.Entities
{
    public partial class mb_Hall
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int TheatreID
        {
            get { return _theatreID; }
            set
            {
                if (_theatreID != value)
                {
                    if (mb_Theatre != null && mb_Theatre.ID != value)
                    {
                        mb_Theatre = null;
                    }
                    _theatreID = value;
                }
            }
        }
        private int _theatreID;
    
        public virtual string HallName
        {
            get;
            set;
        }
    
        public virtual int TotalSeats
        {
            get;
            set;
        }
    
        public virtual bool Active
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual mb_Theatre mb_Theatre
        {
            get { return _mb_Theatre; }
            set
            {
                if (!ReferenceEquals(_mb_Theatre, value))
                {
                    var previousValue = _mb_Theatre;
                    _mb_Theatre = value;
                    Fixupmb_Theatre(previousValue);
                }
            }
        }
        private mb_Theatre _mb_Theatre;

        #endregion
        #region Association Fixup
    
        private void Fixupmb_Theatre(mb_Theatre previousValue)
        {
            if (previousValue != null && previousValue.mb_Hall.Contains(this))
            {
                previousValue.mb_Hall.Remove(this);
            }
    
            if (mb_Theatre != null)
            {
                if (!mb_Theatre.mb_Hall.Contains(this))
                {
                    mb_Theatre.mb_Hall.Add(this);
                }
                if (TheatreID != mb_Theatre.ID)
                {
                    TheatreID = mb_Theatre.ID;
                }
            }
        }

        #endregion
    }
}
