//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MovieBooking.Model.Entities
{
    public partial class mb_Theatre
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string PostalCode
        {
            get;
            set;
        }
    
        public virtual string PhoneNo
        {
            get;
            set;
        }
    
        public virtual string FaxNo
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual string WebSite
        {
            get;
            set;
        }
    
        public virtual bool Active
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mb_Hall> mb_Hall
        {
            get
            {
                if (_mb_Hall == null)
                {
                    var newCollection = new FixupCollection<mb_Hall>();
                    newCollection.CollectionChanged += Fixupmb_Hall;
                    _mb_Hall = newCollection;
                }
                return _mb_Hall;
            }
            set
            {
                if (!ReferenceEquals(_mb_Hall, value))
                {
                    var previousValue = _mb_Hall as FixupCollection<mb_Hall>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmb_Hall;
                    }
                    _mb_Hall = value;
                    var newValue = value as FixupCollection<mb_Hall>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmb_Hall;
                    }
                }
            }
        }
        private ICollection<mb_Hall> _mb_Hall;
    
        public virtual ICollection<mb_MovieSchedule> mb_MovieSchedule
        {
            get
            {
                if (_mb_MovieSchedule == null)
                {
                    var newCollection = new FixupCollection<mb_MovieSchedule>();
                    newCollection.CollectionChanged += Fixupmb_MovieSchedule;
                    _mb_MovieSchedule = newCollection;
                }
                return _mb_MovieSchedule;
            }
            set
            {
                if (!ReferenceEquals(_mb_MovieSchedule, value))
                {
                    var previousValue = _mb_MovieSchedule as FixupCollection<mb_MovieSchedule>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmb_MovieSchedule;
                    }
                    _mb_MovieSchedule = value;
                    var newValue = value as FixupCollection<mb_MovieSchedule>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmb_MovieSchedule;
                    }
                }
            }
        }
        private ICollection<mb_MovieSchedule> _mb_MovieSchedule;

        #endregion
        #region Association Fixup
    
        private void Fixupmb_Hall(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mb_Hall item in e.NewItems)
                {
                    item.mb_Theatre = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mb_Hall item in e.OldItems)
                {
                    if (ReferenceEquals(item.mb_Theatre, this))
                    {
                        item.mb_Theatre = null;
                    }
                }
            }
        }
    
        private void Fixupmb_MovieSchedule(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mb_MovieSchedule item in e.NewItems)
                {
                    item.mb_Theatre = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mb_MovieSchedule item in e.OldItems)
                {
                    if (ReferenceEquals(item.mb_Theatre, this))
                    {
                        item.mb_Theatre = null;
                    }
                }
            }
        }

        #endregion
    }
}
